// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "cmedpanel.H"
#include "cmed.H"

Fl_Button *undobutton=(Fl_Button *)0;

Fl_Button *loadbtn=(Fl_Button *)0;

Fl_Button *savebtn=(Fl_Button *)0;

Fl_Slider *forceslider=(Fl_Slider *)0;

Fl_Button *rgbmode=(Fl_Button *)0;

Fl_Input *fnamebox=(Fl_Input *)0;

class CMedit *cmedit=(class CMedit *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(390, 450);
    w = o;
    { Fl_Button* o = undobutton = new Fl_Button(5, 0, 40, 25, "Undo");
      o->down_box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)undo_cb);
    }
    { Fl_Button* o = loadbtn = new Fl_Button(55, 0, 45, 25, "Load");
      o->callback((Fl_Callback*)fload_cb);
    }
    { Fl_Button* o = savebtn = new Fl_Button(110, 0, 45, 25, "Save");
      o->callback((Fl_Callback*)fsave_cb);
    }
    { Fl_Slider* o = forceslider = new Fl_Slider(205, 0, 75, 25, "Force");
      o->type(5);
      o->selection_color((Fl_Color)1);
      o->minimum(0.05);
      o->value(0.5);
      o->callback((Fl_Callback*)lerp_cb);
      o->align(FL_ALIGN_RIGHT);
    }
    { Fl_Button* o = rgbmode = new Fl_Button(330, 0, 35, 25, "HSB");
      o->labelsize(12);
      o->callback((Fl_Callback*)rgbmode_cb);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Input* o = fnamebox = new Fl_Input(30, 35, 355, 25, "File:");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(12);
      o->callback((Fl_Callback*)input_cb);
      o->when(FL_WHEN_ENTER_KEY_ALWAYS);
    }
    { Fl_Box* o = cshow.hsblbls[0] = new Fl_Box(30, 60, 80, 20, "Hue (L)");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)34);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor((Fl_Color)3);
    }
    { Fl_Box* o = cshow.hsblbls[1] = new Fl_Box(115, 60, 75, 20, "Sat(M)");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)34);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor((Fl_Color)2);
    }
    { Fl_Box* o = cshow.hsblbls[2] = new Fl_Box(195, 60, 75, 20, "Bright(R)");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)34);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor((Fl_Color)235);
    }
    { Fl_Box* o = new Fl_Box(275, 60, 80, 20, "Alpha(shift)");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)34);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
    }
    { class CMedit* o = cmedit = new class CMedit(5, 85, 380, 270);
      o->box(FL_FLAT_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    { colorpatch* o = cshow.color = new colorpatch(60, 360, 50, 40);
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NO_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_Value_Input* o = cshow.cindex = new Fl_Value_Input(5, 375, 50, 25, "  (index");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)16);
      o->maximum(0);
      o->step(1);
      o->textsize(12);
      o->callback((Fl_Callback*)report_cb);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_Output* o = cshow.hsba = new Fl_Output(115, 375, 120, 25, "HSBA");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)16);
      o->textsize(11);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_Output* o = cshow.rgba = new Fl_Output(245, 375, 125, 25, "rgb");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)16);
      o->textsize(11);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_Value_Input* o = cshow.postscalein = new Fl_Value_Input(315, 420, 65, 25, "* Amax");
      o->callback((Fl_Callback*)ascale_cb);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Value_Input* o = cshow.postexponin = new Fl_Value_Input(235, 420, 75, 25, "**  expon  )");
      o->callback((Fl_Callback*)ascale_cb);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Value_Input* o = cshow.cmentin = new Fl_Value_Input(5, 420, 55, 25, "cmapsize");
      o->box(FL_ENGRAVED_BOX);
      o->color((Fl_Color)25);
      o->callback((Fl_Callback*)ncment_cb);
      o->align(FL_ALIGN_TOP_LEFT);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_Output* o = cshow.scaleout = new Fl_Output(135, 420, 95, 25, "  Aout  =  ( Ain");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)16);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    o->end();
  }
  return w;
}
